### ISSUE TITLE
[TODO/baseEntity] BaseEntity 기존 설정의 위험

### ISSUE THREAD

**Issue by JGoo99** [SamCoMo/DBZ-Backend#17]
## 💡 Description

생성시간과 수정시간을 자동으로 할당하기 위해 사용하는 `baseEntity` 의 설정 수정이 필요합니다.

<br/>

**1. 클래스 타입을 abstract 로 변경합니다.**

baseEntity 자체를 생성하여 사용할 일은 없기 때문에 상속하여 쓰도록 강제합니다.

```java
// 변경 이전
public class BaseEntity { ... }

// 변경 이후
public abstract class BaseEntity { ... }
```

<br/><br/>

**2. 문제가 되는 어노테이션을 삭제하고 필요한 어노테이션만 추가합니다.**

문제가 되는 어노테이션은 아래와 같습니다.

```java
// 변경 이전

// 부모
@Getter
@EntityListeners(value = {AuditingEntityListener.class})
public class BaseEntity { ... }

// 자식
@Entity
@Getter
@Setter // 1. setter 의 무분별한 사용으로 인한 문제
@Builder // 2. baseEntity 의 필드 초기화 불가 문제
@AllArgsConstructor // 3. 리펙토링으로 필드의 순서를 바꿨을 때 검출 불가
@NoArgsConstructor // 4. 아무런 값을 갖지 않는 무분별한 생성 문제
public class Member extends BaseEntity { ... }
```

> 1. 어노테이션으로 생성된 setter 는 어떤 위치에서 수정이 이루어졌는지 추적하기가 어려워 문제가 발생했을 때 리펙토링이 곤란합니다.
>
> 2. 상속한 클래스의 필드를 초기화하기 위해선 부모 클래스에 `@MappedSuperClass`를 추가하고, 두 클래스 모두 `@SupperBuilder` 가 필요합니다.
>
> 3. 만약 같은 타입의 필드가 여러개 있는 엔티티의 경우, 특정 필드의 순서를 바꿨을 때 값이 바뀌어 초기화 될 가능성이 높아 아주 위험합니다.
>
> ```java
> // 원래 필드 구성
> public class Ex {
>    private int height;
>    private int Weight;
> }
>
> // 외부 에서 객체 생성
> Ex ex = new Ex(170, 60);
>
> // 만약 필드 순서를 바꾼다면? 몸무게 170kg 에 키 60cm 가 돼버리는..
> public class Ex {
>    private int Weight;
>    private int height;
> }
> ```
>
> 4. 아무런 값을 갖지 않는 생성의 여지가 있으므로 불가피한 상황이 아니면 서비스에 필요한 생성자를 따로 만들어 사용하는 것이 좋습니다.
>
> ```java
> // 변경 이후
>
> // 부모
> @Getter
> @SuperBuilder
> @MappedSuperclass
> @NoArgsConstructor
> @EntityListeners(value = {AuditingEntityListener.class})
> public abstract class BaseEntity { ... }
> 
> // 자식
> @Entity
> @Getter
> @SuperBuilder
> @NoArgsConstructor(access = AccessLevel.PROTECTED)
> public class Member extends BaseEntity { ... }
> ```

<br/>

## 🚗 Todo

- [x] BaseEntity 클래스 타입을 abstract 로 변경하기
- [x] 어노테이션 수정하기

<br/>
## 📚 References

[@AllArgsContructor 의 위험성에 대한 글](https://siahn95.tistory.com/170#%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD%20%EB%B0%8F%20%EB%8B%A8%EC%A0%90-1)
[(velog)올바른 Lombok 사용법](https://dev-jhl.tistory.com/entry/Lombok-%EC%98%AC%EB%B0%94%EB%A5%B8-Lombok-%EC%82%AC%EC%9A%A9%EB%B2%95-Builder)

**Comment by Cassiiopeia** [comment]
1. 오 그러네요 baseEntity가 class로 설정되어있으면 안됐네요. 상속을 통해서 관리하여야할것같습니다. 허허... 제가 생각이 짧게 구현한것같아 민망하네요

2. @Setter라는 전체적인값을 만드는게 아닌 클래스안에 Setter기능을 사용할 메서드를 따로 만들자라는 말씀이신가요?

    public void changeNickname(String nickname) {
        this.nickname = nickname;
    }
    
  이런식으로 말씀이신가죠? 
  저희가 Member 수정에 대한 부분이 ImageUrl 밖에 없는것 같더라고요
  프로필 사진 수정, 삭제하기 밖에 없는것같아서 @Setter를 삭제하는것이 더 바람직한것 같습니다.

하지만 Report같은 수정이 지속적으로 필요한 Entity는 @Setter를 유지하는것이 좋지 않을까요?

3. @SuperBuilder를 사용하여 BaseEntity를 명시적으로 초기화할 이유가 있을까요??

Member.builder()
.createdAt(LocalDateTime.now())
.build();

이렇게 따로 명시하지 않아도 updatedAt과 createdAt은 잘 관리되는거 아닌가요? 이유가 궁금합니다

4. @AllArgsConstructor 에 대한 지식을 얻고갑니다. 여태껏 Builder로 명시했어서 잘 몰랐던 부분이네요! 

5. @NoArgsConstructor(access = AccessLevel.PROTECTED) 이부분을 Protected로 바꾸면 어떤것이 달라지나요?

Entity에 대해 Lombok 어노테이션을 잘 고민해서 사용해야되겠어요! 잘 봤습니다!

**Comment by JGoo99** [comment]
> 2. 하지만 Report같은 수정이 지속적으로 필요한 Entity는 Setter를 유지하는것이 좋지 않을까요?

setter 자체를 지양하는 이유가 크게 두가지인데요.
첫째로 setter 를 이용해서 필드값을 수정하면 왜 수정했는지를 코드를 다 읽어봐야 이해할 수 있어요. 객체지향에서 좀 벗어난 느낌이 있습니다.
둘째로 setter는 생성할 때 public 으로 생성하게 돼서 어느 곳에서나 필드값을 변경할 수 있어요. 만약 게시글에 있는 회원정보를 외부에서 바꾸게되면 오류 발생도 쉽고 신뢰성도 떨어집니다!

그래서 저는 이렇게 해요. **게시글 상태 수정(완료처리)** 을 예시로 들게요!

- 엔티티 클래스 내에 업데이트하는 메소드 생성하기

```java
class Report extends BaseEntity {

    // 필드 생략

    @Enumerated(EnumType.STRING)
    private PetType petType;

    // 매개변수를 받아서 변경하거나
    public void changeReportStatus(ReportStatus reportStatus) {
        this.reportStatus = reportStatus;
    }

    // 매개변수 없이 완료상태로 변경하거나
    public void changeReportStatusToFound() {
        this.reportStatus = FOUND;
    }
}
```

- 외부에서 게시글 수정작업이 이루어질 때 메소드 호출하기

```java
//  기존 setter 방식
report.setReportStatus(FOUND);


// 변경 이후 방식 1
report.changeReportStatus(FOUND);
// 변경 이후 방식 2
report.changeReportStatusToFound();
```

확실히 "게시글 상태 수정" 이라는 의미를 잘 내포하고 있어서 어떤 작업이 이루어지는지 파악하기 쉽고, 어디서 수정이 이루어졌는지 추적하기도 쉽다고 생각해요.
그리고 많은 수정이 이루어져야 하는 것도 jpa 에는 변경을 감지할 수 있는 기능이 있어서 문제가 되지 않는다고 생각합니다!

<br/><br/>

> 3. @SuperBuilder를 사용하여 BaseEntity를 명시적으로 초기화할 이유가 있을까요??

그렇네요! 이슈에 집중하느라 가장 기본 개념을 놓쳤네요..ㅋㅋㅋ @SuperBuilder 는 안 쓰는 것이 맞습니다!
Builder 랑 NoArgsConstructor 를 같이쓰면 충돌이 일어나는데 해결방법은 commit 에 이슈 연동해서 올릴게요.

<br/><br/>

> 5. @NoArgsConstructor(access = AccessLevel.PROTECTED) 이부분을 Protected로 바꾸면 어떤것이 달라지나요?

protected 로 바꾸게 되면 `Member member = new Member();` 로 기본생성자로 객체를 생성했을 때 컴파일 에러가 뜨게되는데 이를 이용하면 매개변수 없는 객체생성을 막을 수 있게돼요!
사실 엔티티에서의 매개변수 없는 기본생성자는 jpa 에서 필요로 하니까 어노테이션으로 선언하는 것 뿐이지 서비스 완성도를 고려했을 때 저희가 사용해야 할 이유는 거의 없다고 생각해요. 그래서 protected 로 필드 초기화 방식을 강제하는 방법을 제안했습니다!

**Comment by Cassiiopeia** [comment]
@JGoo99 

Setter말고 메서드로 표시할시 더 직관적으로 어떤기능인지 알수있군요 
@NoArgsConstructor(access = AccessLevel.PROTECTED) 를 사용하면 잘못된 코드를 방지할수가있군요

좋은 정보감사합니다.
