### ISSUE TITLE
[BUG/MEMBER] JWT 토큰 사용시 Member 검증 로직 이슈

### ISSUE THREAD

**Issue by Cassiiopeia** [SamCoMo/DBZ-Backend#51]
## 💡 Description
현재 각 Controller에서 Member를 검증하는 로직들이 있습니다.

하지만 이는 이미 Authentication authentication 을 가져올때 
member에 대한 여부를 확인하기때문에 검증할 필요가 없어야합니다.

하지만 현재 JWT 필터에서 무조건적인 Member객체를 생성하는것 같습니다.

JwtFilter 에 있는 코드입니다.

    String email = jwtUtil.getEmail(accessToken);
    MemberRole role = MemberRole.get(jwtUtil.getRole(accessToken));

    Member member = Member.builder()
        .email(email)
        .role(role)
        .build();

    MemberDetails memberDetails = new MemberDetails(member);
    
이부분이 그 부분인데요

      @Service
      @RequiredArgsConstructor
      public class MemberDetailsServiceImpl implements UserDetailsService {
      
        private final MemberRepository memberRepository;
      
        @Override
        public MemberDetails loadUserByUsername(String email) throws UsernameNotFoundException {
      
          Member member = memberRepository.findByEmail(email).orElseThrow(() ->
              new MemberException(MEMBER_NOT_FOUND));
      
          return new MemberDetails(member);
        }
      }

MemberDetailsServiceImpl에서 loadUserByUsername에서 member에 대한 여부를 확인하고 MemberDetails 를 반환하는 로직이 있는데 

사용하고있지 않습니다. 

위에 코드부분을 이미 구현해놓은 loadUserByUsername() 로 대체해야할것같습니다. 

그렇게되면 각 API의 Controller들에서 member를 검증하는 로직은 없어도 될것같습니다. 

member에 대한 전체 객체가 필요없다라고하면
existsByEmail 로 member가 있는지 여부만 확인하고

    public MemberDetails loadUserByUsername(String email) throws UsernameNotFoundException {
                            
    memberRepository.existsByEmail(email).orElseThrow(() ->
    new MemberException(MEMBER_NOT_FOUND));
                                    
    return new MemberDetails(Member.builder().email(email).role(role).build());
    }
  
  와 같은식으로 수정하는것도 좋을것 같습니다.
  
  
### findByEmail , existsByEmail
---
만약 member가 존재하는 여부를 검증하는 로직이 따로 필요하다면
findByEmail 을 통해 member로 검색하는것보다

Boolean existsByEmail(String email) 로 받아서 사용하게되면 DB 전체조회를 하지않고 존재여부만 빠르게 알 수 있을것 같습니다.

**Comment by JGoo99** [comment]
> MemberDetailsServiceImpl에서 loadUserByUsername에서 member에 대한 여부를 확인하고 MemberDetails 를 반환하는 로직이 있는데 사용하고있지 않습니다.

우선 loadUserByUsername 은 제가 호출하기 위해서 구현한 것이기 보단, 스프링 필터 내에서 호출되기 때문에 구현했습니다! (물론 제가 사용할 수도 있지만요.)

UserDetailsService 를 구현한 클래스를 필터에서 호출했을 때 회원의 아이디(name)와 비밀번호 정보가 있는 UserDetails 구현체를 반환하는 메소드가 있어야 로그인 진행이 되거든요! 실제로 UserDetailsService 없이 로그인을 진행하면 아래 에러가 반환됩니다.

```
2024-03-14T18:43:39.719+09:00 ERROR 28346 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause
```

[스프링 공식 문서 참고해주세요.](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/dao-authentication-provider.html#page-title)

아래는 UserDetails 를 UserDetailsService 를 이용하여 호출하는 부분입니다.
```java
public class DaoAuthenticationProvider extends AbstractUserDetailsAuthenticationProvider {

  private UserDetailsService userDetailsService;

  public void setUserDetailsService(UserDetailsService userDetailsService) {
    this.userDetailsService = userDetailsService;
  }

  // 생략

  @Override
  protected final UserDetails retrieveUser(String username, UsernamePasswordAuthenticationToken authentication) throws AuthenticationException {

    prepareTimingAttackProtection();

    try {
      UserDetails loadedUser = this.getUserDetailsService().loadUserByUsername(username);

      // 생략
    } catch (Exception ex) {
        ...
    }
  }

  protected UserDetailsService getUserDetailsService() {
    return this.userDetailsService;
  }
}
```

**Comment by JGoo99** [comment]
> 위에 코드부분을 이미 구현해놓은 loadUserByUsername() 로 대체해야할것같습니다.

위 메소드를 사용하면 멤버에 대한 모든 정보를 가져와서 세션에 담게됩니다. 

- 기존 코드

```java
Member member = Member.builder()
    .email(email)
    .role(role)
    .build();

MemberDetails memberDetails = new MemberDetails(member);

Authentication authToken = new UsernamePasswordAuthenticationToken(
    memberDetails, null, memberDetails.getAuthorities());

// email, role 을 세션에 담음.
SecurityContextHolder.getContext().setAuthentication(authToken);
```


```java
MemberDetails memberDetails = memberDetailsService.loadUserByUsername(email);

Authentication authToken = new UsernamePasswordAuthenticationToken(
    memberDetails, null, memberDetails.getAuthorities());

// member DB 의 모든 정보를 세션에 담음.
SecurityContextHolder.getContext().setAuthentication(authToken);
```

**Comment by JGoo99** [comment]
넵 맞습니다! email -> id 로 리펙터링한 pr 올렸으니 확인 부탁드려요!👍🏻
